name: Power BI Deployment

trigger:
- Master

variables:
  pbiFile: '**.pbix'
  workspaceId: '48a697cb-60f6-4efc-b80c-c1f0eedf3cb1'

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - script: |
        # Perform any necessary build steps here, such as compiling source code
        echo "Building report..."
      displayName: 'Build Report'

- stage: Deploy
  jobs:
  - job: Deploy
    steps:
    - script: |
        # Install the Power BI command-line interface (CLI)
        echo "Installing Power BI CLI..."
        npm install -g powerbi-cli
        pip install pytest pytest-azurepipelines
        pip install msal

        # Authenticate with Power BI using python script
        echo "Authenticating with Power BI using python script..."
        python powerbi1.py
  - task: AzurePowerBIDeployment@1
        inputs:
        connectionName: 'powerbi'
        datasetName: 'powerbi'
        pbiFile: '$(pbiFile)'
        workspaceId: '$(workspaceId)'

