name: Power BI Deployment

trigger:
- Master

variables:
  - name: powerbi_file
    value: 'powerbi_demo1.pbix'

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - script: |
        # Perform any necessary build steps here, such as compiling source code
        echo "Building report..."
      displayName: 'Build Report'

- stage: Deploy
  jobs:
  - job: Deploy
    steps:
    - script: |
        # Install the Power BI command-line interface (CLI)
        echo "Installing Power BI CLI..."
        npm install -g powerbi-cli
        pip install pytest pytest-azurepipelines
        pip install msal

        # Authenticate with Power BI using python script
        echo "Authenticating with Power BI using python script..."
        python powerbi1.py

        # Import the report
        echo "Importing report..."
        pbi import -f $(powerbi_file) -n "My Report"

        # Publish the report
        echo "Publishing report..."
        pbi publish -n "My Report"

        # Sign out of Power BI
        echo "Signing out of Power BI..."
        pbi logout
      displayName: 'Deploy Report'

